// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbbkLYvASzAYo8IxZrr4vgUBYW_8pupo',
    appId: '1:229314031683:web:3407361d2db1fd63d8e4f6',
    messagingSenderId: '229314031683',
    projectId: 'catalog-add-69226',
    authDomain: 'catalog-add-69226.firebaseapp.com',
    storageBucket: 'catalog-add-69226.appspot.com',
    measurementId: 'G-Y83GDLL5FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_zz1_dM_vKbCawRNMVD5ZjYLlos62x4',
    appId: '1:229314031683:android:73826789036dd148d8e4f6',
    messagingSenderId: '229314031683',
    projectId: 'catalog-add-69226',
    storageBucket: 'catalog-add-69226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyu8Mao1UexlVV4UESlyRmHaCvaMcBW6U',
    appId: '1:229314031683:ios:a613b5bc1847a197d8e4f6',
    messagingSenderId: '229314031683',
    projectId: 'catalog-add-69226',
    storageBucket: 'catalog-add-69226.appspot.com',
    iosBundleId: 'com.example.nativeDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyu8Mao1UexlVV4UESlyRmHaCvaMcBW6U',
    appId: '1:229314031683:ios:a613b5bc1847a197d8e4f6',
    messagingSenderId: '229314031683',
    projectId: 'catalog-add-69226',
    storageBucket: 'catalog-add-69226.appspot.com',
    iosBundleId: 'com.example.nativeDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbbkLYvASzAYo8IxZrr4vgUBYW_8pupo',
    appId: '1:229314031683:web:f3b197faa5f16f83d8e4f6',
    messagingSenderId: '229314031683',
    projectId: 'catalog-add-69226',
    authDomain: 'catalog-add-69226.firebaseapp.com',
    storageBucket: 'catalog-add-69226.appspot.com',
    measurementId: 'G-78RYE7BL85',
  );
}
